version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file: ./.env
    volumes:
      - ~/mongodb_data_aitc:/data/db
    networks:
      - aitc

  socialappapi:
    image: socialappapi_image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socialappapi
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - aitc

networks:
  aitc:
    driver: bridge
